Repository meta-pytorch/tokenizers, pull requests merged in 2025-10, with the labels that each got.

#130 Add Phi4 test and fix regex parsing.
  src/hf_tokenizer.cpp
  src/pre_tokenizer.cpp
  test/test_hf_tokenizer.py
  third-party/targets.bzl
Labels: CLA Signed, fb-exported, meta-exported

#133 Remove TARGETS file that shouldn't be synced
  test/fb/TARGETS
Labels: CLA Signed

#134 Revert "[Windows] Fix build issues using Clang-CL on Windows, add CI …
  .github/workflows/pull.yml
  .gitignore
  CMakeLists.txt
  include/pytorch/tokenizers/compiler.h
  include/pytorch/tokenizers/tiktoken.h
  setup.py
  src/hf_tokenizer.cpp
  test/test_tiktoken.cpp
Labels: CLA Signed, ci-no-td
