Repository meta-pytorch/tokenizers, pull requests merged in 2025-02, with the labels that each got.

#14 Format
  .github/workflows/pull.yml
  .github/workflows/trunk.yml
  CMakeLists.txt
  CONTRIBUTING.md
  include/base64.h
  include/detail/bpe_tokenizer_base.h
  include/error.h
  include/hf_tokenizer.h
  include/log.h
  include/pre_tokenizer.h
  include/result.h
  include/sentencepiece.h
  include/tiktoken.h
  include/token_decoder.h
  include/tokenizer.h
  src/bpe_tokenizer_base.cpp
  src/hf_tokenizer.cpp
  src/pre_tokenizer.cpp
  src/sentencepiece.cpp
  src/tiktoken.cpp
  src/token_decoder.cpp
  test/test_pre_tokenizer.cpp
  test/test_sentencepiece.cpp
  test/test_tiktoken.cpp
  tools/tokenize_tool/main.cpp
Labels: CLA Signed

#15 Pull machine
  .github/workflows/pull.yml
Labels: CLA Signed, ciflow/trunk

#17 Buckify tokenizers
  CMakeLists.txt
  TARGETS
  include/detail/bpe_tokenizer_base.h
  include/pre_tokenizer.h
  include/sentencepiece.h
  include/token_decoder.h
  src/bpe_tokenizer_base.cpp
  src/hf_tokenizer.cpp
  src/pre_tokenizer.cpp
  src/tiktoken.cpp
  src/token_decoder.cpp
  targets.bzl
  test/resources/test_bpe_tokenizer.bin
  test/resources/test_tiktoken_invalid_base64.model
  test/resources/test_tiktoken_invalid_rank.model
  test/resources/test_tiktoken_no_space.model
  test/resources/test_tiktoken_tokenizer.model
  test/test_pre_tokenizer.cpp
  test/test_sentencepiece.cpp
  test/test_tiktoken.cpp
  third-party/llama.cpp-unicode/include/unicode-data.h
  third-party/llama.cpp-unicode/src/unicode-data.cpp
  third-party/llama.cpp-unicode/src/unicode.cpp
Labels: CLA Signed, ciflow/trunk/all, ciflow/trunk, fb-exported

#19 Add llama2.c tokenizers
  README.md
  include/llama2c_tokenizer.h
  src/llama2c_tokenizer.cpp
  targets.bzl
  test/resources/test_llama2c_tokenizer.bin
  test/test_llama2c_tokenizer.cpp
  tools/llama2c/TARGETS
  tools/llama2c/__init__.py
  tools/llama2c/convert.py
  tools/llama2c/targets.bzl
Labels: CLA Signed, fb-exported

#22 Migrate extension/llm/tokenizer python users to use the new repo
  pytorch_tokenizers/TARGETS
  pytorch_tokenizers/__init__.py
  pytorch_tokenizers/hf_tokenizer.py
  pytorch_tokenizers/llama2c.py
  pytorch_tokenizers/targets.bzl
  pytorch_tokenizers/tiktoken.py
  tools/llama2c/convert.py
  tools/llama2c/targets.bzl
Labels: CLA Signed, fb-exported

#23 Migrate helios' usage of extension/llm/tokenizer to pytorch/tokenizers
  examples/tokenize_tool/CMakeLists.txt
  examples/tokenize_tool/main.cpp
  pytorch_tokenizers/tools/llama2c/TARGETS
  pytorch_tokenizers/tools/llama2c/__init__.py
  pytorch_tokenizers/tools/llama2c/convert.py
  pytorch_tokenizers/tools/llama2c/targets.bzl
Labels: CLA Signed, fb-exported

#21 Tokenizer test
  targets.bzl
  test/TARGETS
  test/targets.bzl
  test/test_llama2c_tokenizer.cpp
  test/test_sentencepiece.cpp
  test/test_tiktoken.cpp
Labels: CLA Signed, fb-exported

#24 Add setup.py
  pyproject.toml
  pytorch_tokenizers/tools/llama2c/convert.py
  setup.py
Labels: CLA Signed
