Repository meta-pytorch/tokenizers, pull requests merged in 2025-07, with the labels that each got.

#93 Add support for more behavior in Split pretokenizer
  include/pytorch/tokenizers/pre_tokenizer.h
  src/pre_tokenizer.cpp
  test/test_isolated_behavior.cpp
  test/test_pre_tokenizer.cpp
Labels: CLA Signed

#95 Fix test_hf_tokenizer
  test/targets.bzl
Labels: CLA Signed

#96 Support gemma3 HF tokenizer.json
  CMakeLists.txt
  include/pytorch/tokenizers/bpe_tokenizer_base.h
  include/pytorch/tokenizers/hf_tokenizer.h
  include/pytorch/tokenizers/llama2c_tokenizer.h
  include/pytorch/tokenizers/normalizer.h
  include/pytorch/tokenizers/tokenizer.h
  src/bpe_tokenizer_base.cpp
  src/hf_tokenizer.cpp
  src/llama2c_tokenizer.cpp
  src/normalizer.cpp
  src/tiktoken.cpp
  targets.bzl
  test/resources/test_hf_tokenizer.json
  test/targets.bzl
  test/test_normalizer.cpp
Labels: CLA Signed

#100 Only run python test in fbcode
  test/TARGETS
  test/targets.bzl
Labels: CLA Signed, fb-exported

#104 Support NFC Normalizer
  include/pytorch/tokenizers/normalizer.h
  src/normalizer.cpp
  test/test_hf_tokenizer.py
  third-party/llama.cpp-unicode/include/unicode.h
  third-party/llama.cpp-unicode/src/unicode.cpp
Labels: CLA Signed, ciflow/trunk

#107 Remove unused file
  Package.swift
Labels: CLA Signed

#108 Fix lint issues
  test/TARGETS
  test/test_hf_tokenizer.py
Labels: CLA Signed

#112 Rename build files from TARGETS to BUCK (group ID: -4292110907067644689)
  TARGETS
  pytorch_tokenizers/TARGETS
  pytorch_tokenizers/tools/llama2c/TARGETS
  test/TARGETS
  third-party/TARGETS
Labels: CLA Signed, fb-exported
