Repository meta-pytorch/tokenizers, pull requests merged in 2025-03, with the labels that each got.

#25 Fix tiktoken test
  include/pytorch/tokenizers/tiktoken.h
Labels: CLA Signed, ciflow/trunk/all, fb-exported

#26 Add a TARGETS file for executorch's buck build in oss
  third-party/TARGETS
Labels: CLA Signed, ciflow/trunk/all

#28 Use executorch's glob_defs.bzl
  targets.bzl
Labels: CLA Signed

#27 Extending build systems to include FBCode
  targets.bzl
Labels: CLA Signed, fb-exported

#29 Add override to destructor
  .flake8
  .lintrunner.toml
  .mypy.ini
  examples/tokenize_tool/main.cpp
  include/pytorch/tokenizers/base64.h
  include/pytorch/tokenizers/bpe_tokenizer_base.h
  include/pytorch/tokenizers/error.h
  include/pytorch/tokenizers/hf_tokenizer.h
  include/pytorch/tokenizers/llama2c_tokenizer.h
  include/pytorch/tokenizers/log.h
  include/pytorch/tokenizers/pre_tokenizer.h
  include/pytorch/tokenizers/result.h
  include/pytorch/tokenizers/sentencepiece.h
  include/pytorch/tokenizers/tiktoken.h
  include/pytorch/tokenizers/token_decoder.h
  include/pytorch/tokenizers/tokenizer.h
  pytorch_tokenizers/tools/llama2c/convert.py
  requirements-lintrunner.txt
  setup.py
  src/bpe_tokenizer_base.cpp
  src/hf_tokenizer.cpp
  src/llama2c_tokenizer.cpp
  src/pre_tokenizer.cpp
  src/sentencepiece.cpp
  src/tiktoken.cpp
  src/token_decoder.cpp
  test/test_base64.cpp
  test/test_llama2c_tokenizer.cpp
  test/test_pre_tokenizer.cpp
  test/test_sentencepiece.cpp
  test/test_tiktoken.cpp
Labels: CLA Signed

#30 Fix clang format
  include/pytorch/tokenizers/base64.h
  include/pytorch/tokenizers/bpe_tokenizer_base.h
  include/pytorch/tokenizers/error.h
  include/pytorch/tokenizers/hf_tokenizer.h
  include/pytorch/tokenizers/llama2c_tokenizer.h
  include/pytorch/tokenizers/log.h
  include/pytorch/tokenizers/pre_tokenizer.h
  include/pytorch/tokenizers/result.h
  include/pytorch/tokenizers/sentencepiece.h
  include/pytorch/tokenizers/tiktoken.h
  include/pytorch/tokenizers/token_decoder.h
  include/pytorch/tokenizers/tokenizer.h
  src/bpe_tokenizer_base.cpp
  src/hf_tokenizer.cpp
  src/llama2c_tokenizer.cpp
  src/pre_tokenizer.cpp
  src/sentencepiece.cpp
  src/tiktoken.cpp
  src/token_decoder.cpp
Labels: CLA Signed

#31 Update bpe_tokenizer_base.h
  include/pytorch/tokenizers/bpe_tokenizer_base.h
Labels: CLA Signed

#32 clang format the rest of code
  examples/tokenize_tool/main.cpp
  test/test_base64.cpp
  test/test_llama2c_tokenizer.cpp
  test/test_pre_tokenizer.cpp
  test/test_sentencepiece.cpp
  test/test_tiktoken.cpp
Labels: CLA Signed

#33 Rely on runtime_wrapper to provide supported platforms
  src/pre_tokenizer.cpp
  src/token_decoder.cpp
  targets.bzl
  third-party/TARGETS
  third-party/llama.cpp-unicode/include/unicode-data.h
  third-party/llama.cpp-unicode/include/unicode.h
  third-party/llama.cpp-unicode/src/unicode-data.cpp
  third-party/llama.cpp-unicode/src/unicode.cpp
Labels: CLA Signed

#34 Add .clang-format
  .clang-format
  src/pre_tokenizer.cpp
  src/token_decoder.cpp
  targets.bzl
Labels: CLA Signed

#35 Add TARGETS file for internal build
  third-party/TARGETS
  third-party/targets.bzl
Labels: CLA Signed

#37 Port string_integer_map and changes to tiktoken to pytorch
  CMakeLists.txt
  include/pytorch/tokenizers/bpe_tokenizer_base.h
  include/pytorch/tokenizers/string_integer_map.h
  include/pytorch/tokenizers/tiktoken.h
  src/bpe_tokenizer_base.cpp
  src/hf_tokenizer.cpp
  src/tiktoken.cpp
  test/fb/TARGETS
  test/targets.bzl
  test/test_string_integer_map.cpp
Labels: CLA Signed, fb-exported

#39 Remove old tokenizer/ directory in ExecuTorch
  pytorch_tokenizers/tools/__init__.py
  pytorch_tokenizers/tools/llama2c/convert.py
  pytorch_tokenizers/tools/llama2c/targets.bzl
  setup.py
  tools/llama2c/convert.py
  tools/llama2c/targets.bzl
Labels: CLA Signed, fb-exported
